---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main
  name: main
spec:
  replicas: 5
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - image: nginx:1.28
          name: main
          ports:
            - containerPort: 80
      restartPolicy: Always