---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main
  name: main
spec:
  replicas: 5
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - image: nginx:1.19
          name: main
          ports:
            - containerPort: 80
      restartPolicy: Always