---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  replicas: 1
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:13-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: news
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: db
  name: db
spec:
  ports:
    - name: db
      port: 5432
      targetPort: 5432
  selector:
    app: db
  type: ClusterIP