apiVersion: v1
kind: Pod
metadata:
  name: shared-volume
spec:
  containers:
    - name: backend
      image: roma4edu/netology_kube_backend:1.0
      env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@db.stage.svc.cluster.local:5432/news
      ports:
        - containerPort: 9000
      volumeMounts:
        - mountPath: "/static"
          name: my-volume
    - name: frontend
      image: roma4edu/netology_kube_frontend:1.0
      ports:
        - containerPort: 80
      env:
        - name: BASE_URL
          value: http://localhost:9000
      volumeMounts:
        - mountPath: "/static"
          name: my-volume
  volumes:
    - name: my-volume
      emptyDir: {}